/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package arg.edu.iua.presentacion;

import arg.edu.iua.modelo.Usuario;
import javax.swing.JFrame;

/**
 *
 * @author Octavio
 */
public class MainMenu extends javax.swing.JFrame {
    Usuario u=new Usuario();
    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    }

    MainMenu(Usuario us) {
     u=us;
     initComponents();
     
     
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jNombre = new javax.swing.JLabel();
        jApellido = new javax.swing.JLabel();
        jNombreU = new javax.swing.JLabel();
        jContraseña = new javax.swing.JLabel();
        jEdad = new javax.swing.JLabel();
        jEdadU = new javax.swing.JLabel();
        jApellidoU = new javax.swing.JLabel();
        jFN = new javax.swing.JLabel();
        jFnU = new javax.swing.JLabel();
        jNomUsu = new javax.swing.JLabel();
        jContraseñaU = new javax.swing.JLabel();
        jNomUsuU = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(135, 211, 124));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Mi Perfil");
        jLabel1.setToolTipText("");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Publicaciones");
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Contactos");
        jLabel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Cerrar Secion");
        jLabel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(144, 198, 149), null, null));
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 780, 80);

        jPanel3.setBackground(new java.awt.Color(210, 215, 211));

        jPanel4.setBackground(new java.awt.Color(236, 240, 241));
        jPanel4.setLayout(null);

        jNombre.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        jNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jNombre.setText("Nombre:");
        jPanel4.add(jNombre);
        jNombre.setBounds(170, 40, 190, 38);

        jApellido.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        jApellido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jApellido.setText("Apellido:");
        jPanel4.add(jApellido);
        jApellido.setBounds(170, 90, 190, 38);

        jNombreU.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        jNombreU.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jNombreU.setText(u.getNombre());
        jPanel4.add(jNombreU);
        jNombreU.setBounds(410, 40, 131, 38);

        jContraseña.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        jContraseña.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jContraseña.setText("Contraseña:");
        jPanel4.add(jContraseña);
        jContraseña.setBounds(169, 290, 190, 38);

        jEdad.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        jEdad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jEdad.setText("Edad:");
        jPanel4.add(jEdad);
        jEdad.setBounds(170, 140, 190, 38);

        jEdadU.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        jEdadU.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jEdadU.setText(u.getEdad().toString());
        jPanel4.add(jEdadU);
        jEdadU.setBounds(410, 140, 131, 38);

        jApellidoU.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        jApellidoU.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jApellidoU.setText(u.getApellido());
        jPanel4.add(jApellidoU);
        jApellidoU.setBounds(410, 90, 131, 38);

        jFN.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        jFN.setText("Fecha de nacimiernto:");
        jPanel4.add(jFN);
        jFN.setBounds(170, 190, 190, 38);

        jFnU.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        jFnU.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jFnU.setText(u.getFechaNac().toString());
        jPanel4.add(jFnU);
        jFnU.setBounds(410, 190, 131, 38);

        jNomUsu.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        jNomUsu.setText("Nombre de Usuario:");
        jPanel4.add(jNomUsu);
        jNomUsu.setBounds(170, 240, 190, 38);

        jContraseñaU.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        jContraseñaU.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jContraseñaU.setText(u.getUsername());
        jPanel4.add(jContraseñaU);
        jContraseñaU.setBounds(410, 290, 131, 38);

        jNomUsuU.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        jNomUsuU.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jNomUsuU.setText(u.getUsername());
        jPanel4.add(jNomUsuU);
        jNomUsuU.setBounds(410, 240, 131, 38);

        jButton1.setText("Editar datos");
        jPanel4.add(jButton1);
        jButton1.setBounds(590, 370, 120, 23);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 80, 780, 430);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
       Login lgf= new Login();
        lgf.setVisible(true);
        lgf.pack();
        lgf.setLocationRelativeTo(null);
        lgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jApellido;
    private javax.swing.JLabel jApellidoU;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jContraseña;
    private javax.swing.JLabel jContraseñaU;
    private javax.swing.JLabel jEdad;
    private javax.swing.JLabel jEdadU;
    private javax.swing.JLabel jFN;
    private javax.swing.JLabel jFnU;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jNomUsu;
    private javax.swing.JLabel jNomUsuU;
    private javax.swing.JLabel jNombre;
    private javax.swing.JLabel jNombreU;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables


}
